routes/web.php
        'prefix' => $route('post', 'posts'),
    ], function () use ($middleware, $authMiddleware) {

        // All posts view.
        Route::get('/', [
            'as'         => 'index',
            'uses'       => 'ChatterPostController@index',
            'middleware' => $middleware('post.index'),
        ]);

        // Create post view.
        Route::get('create', [
            'as'         => 'create',
            'uses'       => 'ChatterPostController@create',
            'middleware' => $authMiddleware('post.create'),
        ]);

        // Store post action.
        Route::post('/', [
            'as'         => 'store',
            'uses'       => 'ChatterPostController@store',
            'middleware' => $authMiddleware('post.store'),
        ]);

        /*
         * Specific post routes.
         */
        Route::group([
            'prefix' => '{post}',
        ], function () use ($middleware, $authMiddleware) {

            // Single post view.
            Route::get('/', [
                'as'         => 'show',
                'uses'       => 'ChatterPostController@show',
                'middleware' => $middleware('post.show'),
            ]);

            // Edit post view.
            Route::get('edit', [
                'as'         => 'edit',
                'uses'       => 'ChatterPostController@edit',
                'middleware' => $authMiddleware('post.edit'),
            ]);

            // Update post action.
            Route::match(['PUT', 'PATCH'], '/', [
                'as'         => 'update',
                'uses'       => 'ChatterPostController@update',
                'middleware' => $authMiddleware('post.update'),
            ]);

            // Destroy post action.
            Route::delete('/', [
                'as'         => 'destroy',
                'uses'       => 'ChatterPostController@destroy',
                'middleware' => $authMiddleware('post.destroy'),
            ]);
        });
    });
});

/*
 * Atom routes
 */
Route::get($route('home') . '.atom', [
    'as'         => 'chatter.atom',
    'uses'       => 'Chatter\ChatterAtomController@index',
    'middleware' => $middleware('home'),
]);

// ****************************************************
// ********End          *******************************
// ********Forum Routes *******************************
// ****************************************************

Route::group([
    'middleware' => 'auth',
],
    function () {
        Route::get('', 'HomeController@index');
        Route::group([
            'prefix' => 'home',
        ],
            function () {
                Route::get('', 'HomeController@index');
                // drg>> These are routes for JSON requests
                Route::post('getevents', 'HomeController@getEvents');
                Route::post('gettimetable', 'HomeController@getTimeTable');
            });
        Route::group(
            [
                'prefix'     => 'undergraduate',
                'namespace'  => 'student\undergraduate',
                'as'         => 'undergraduate.',
                'middleware' => [
                    'isUndergraduate'
                ]
            ],
            function () {
                Route::group(['prefix' => 'settings', 'as' => 'settings.'],
                    function () {
                        Route::post('guardian',
                            'SettingsController@changeGuardian')
                            ->name('change.guardian');
                        Route::post('guardian/update',
                            'SettingsController@updateGuardian')
                            ->name('update.guardian');

                    });
                Route::get('/search', 'SearchController@index');

                // drg>> routes for undergraduate courses
                Route::group([
                    'prefix' => 'courses'
                ],
                    function () {
                        // drg>> route group to serve notice requests
                        Route::get('', 'CourseController@index');
                        Route::get('register/{action?}',
                            'CourseController@getRegistrationPage');
                        Route::match([
                            'post',
                            'put'
                        ], 'register', 'CourseController@registerCourse');
                        Route::patch('register',
                            'CourseController@updateCourse');
                        Route::get('{page}', 'CourseController@getPage');
                        Route::get('results/{session}',
                            'CourseController@getResults');
                        Route::post('', 'CourseController@getJSON');
                    });
                Route::group([
                    'prefix' => 'fees'
                ],
                    function () {
                        Route::get('/history', 'FeesController@viewHistory');
                        Route::get('/invoice/{id}',
                            'FeesController@viewInvoice');
                        Route::get('/invoices', 'FeesController@viewInvoices');
                        Route::get('/payment', 'FeesController@viewPayment');
                        Route::get('/payment/invoice',
                            'FeesController@paymentInvoice');

                    });
                Route::group([
                    'prefix' => 'messages'
                ],
                    function () {
                        Route::post('/send', 'MessageController@sendMessage');
                        Route::post('/save', 'MessageController@saveMessage');
                        Route::post('/discard',
                            'MessageController@discardMessage');
                        Route::get('/reply/{id}',
                            'MessageController@viewReplyMessage');
                        Route::get('/reply_all/{id}',
                            'MessageController@viewReplyAllMessage');
                        Route::get('/forward/{id}',
                            'MessageController@viewForwardMessage');
                        Route::get('suggest/nodes',
                            'MessageController@suggestNodes');
                        Route::match(['get', 'post'], '/action/{type}',
                            'MessageController@action');
                        Route::get('/{type?}', 'MessageController@index');
                        Route::get('/view/{id}',
                            'MessageController@viewMessage');
                    });
                Route::group([
                    'prefix' => 'notices'
                ],
                    function () {
                        // drg>> route group to serve notice requests
                        Route::get('', 'NoticesController@index');
                        Route::post('',
                            'NoticesController@index'); // drg>> 'post' for form requests only
                        Route::get('{page}', 'NoticesController@index');
                        Route::get('view/{id}', 'NoticesController@display');
                    });

                Route::group([
                    'prefix' => 'verification'
                ],
                    function () {
                        Route::get('', 'VerifyController@index');
                        Route::get('{action}/code',
                            'VerifyController@getCodePage');
                        Route::get('{action}/code/verify',
                            'VerifyController@getRequest');
                        Route::post('{action}/code/verify',
                            'VerifyController@getRequest');
                    });
                Route::get('download/result/{session}/{format}',
                    'DownloadController@result');
                Route::get('download/registration/{format}',
                    'DownloadController@registration');
            });
// drg >> route group for guardian
        Route::group(
            [
                'prefix'     => 'guardian',
                'as'         => 'guardian.',
                'namespace'  => 'guardian',
                'middleware' => 'isGuardian'
            ],
            function () {
                // drg>> routes for urls with prefix "notices"
                Route::group([
                    'prefix' => 'settings',
                    'as'     => 'settings.'
                ],
                    function () {
                        Route::post('profile', 'SettingsController@profile')
                            ->name('profile');
                        Route::post('ward/{ward}/{action}',
                            'SettingsController@ward');
                        Route::post('photo', 'SettingsController@profile')
                            ->name('photo');
                    });
                Route::get('profile', 'GuardianController@viewProfile')
                    ->name('profile');
                Route::group([
                    'prefix' => 'view'
                ],
                    function () {
                        Route::get('/{id}', 'GuardianController@viewWard');
                        Route::post('/{id}/gettimetable',
                            'GuardianController@getTimeTable');
                    });
                Route::group(['prefix' => 'fees'], function () {
                    Route::get('/payment/invoice/{id}',
                        'GuardianController@paymentInvoice');
                });
                Route::get('approve/{action}/{ward}',
                    'GuardianController@approve')->name('approval');
            });
// drg >> route group for staff
        Route::group(
            [
                'prefix'     => 'staff',
                'namespace'  => 'staff',
                'middleware' => [
                    'isStaff'
                ]
            ],
            function () {

app/Http/Controllers/guardian/ChartController.php
<?php

namespace App\Http\Controllers\guardian;

use App\Attendance;
use App\Invoice;
use App\Invoice_line;
use App\Payment;
use App\Services\staff\lecturer\LecturerDataService;
use App\Undergraduate_result;
use App\Users_undergraduate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ChartController extends Controller
{
    //
    public function results($ward)
    {
        $results = Undergraduate_result::where('student_reg_no',
            $ward->name)->select(
            DB::raw('count(result_grade) as count'))
            ->groupBy('result_grade')->orderBy('result_grade', 'desc')
            ->pluck('count');

        return $results;
    }

    public function attendance($remark,$ward)
    {
        $attendance = Attendance::where('signed_user', $ward->name)
            ->where('type', 'lecture')
            ->where('status', 'closed')->where('remark', $remark)
            ->select(DB::raw('count(remark) as count'))->groupBy('session')
            ->orderBy('session')->pluck('count');

        return $attendance;
    }


    public function payments($ward)
    {
        $target = [$ward->dept, $ward->school, $ward->name];
        $currentSession = setting('admin.current_session');
        $year_entry = Users_undergraduate::where('reg_no', $ward->name)
            ->value('year_entry');
        $invoice_id = [];

        $invoices = Invoice::where(function ($query) use (
            $target,
            $year_entry,
            $currentSession
        ) {
            foreach (range($year_entry, $currentSession) as $session) {
                $query->orWhere('session', $session)->whereIn('target', $target)
                    ->orWhere('type', 'university');
                $query->orWhere(function ($query) use (
                    $session,
                    $year_entry,
                    $currentSession
                ) {
                    $query->where('type', 'level')
                        ->where('session', $session)
                        ->where('target',
                            ($currentSession - $session + 1) * 100);
                });
            }
        })->pluck('invoice_id');

        $payment_received = Payment::whereIn('invoice_id',
            $invoices)->where('user_id', $ward->name)->sum('amount');
        $invoiceSum = Invoice_line::whereIn('invoice_id', $invoices)
            ->sum('amount');
        $payment_required = $invoiceSum;
        $paid = $payment_received/100;
        $debt = ($payment_required - $payment_received)/100;

        $payments = [$paid, $debt];


        return $payments;
    }
}

app/Http/Controllers/guardian/GuardianController.php
<?php

namespace App\Http\Controllers\guardian;

use App\Http\Controllers\student\undergraduate\FeesController;
use App\Invoice_line;
use App\TimeTable;
use App\Services\guardian\GuardianDataService;
use App\Services\student\undergraduate\UndergraduateDataService;
use App\User;
use App\Users_guardian;
use App\Users_undergraduate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;

class GuardianController extends Controller
{
    //
    public function approve($action, $ward){
        switch($action){
            case 'accept':
                $wards= $this->getStatus('approved',$ward);

                dd($wards);
                break;
            case 'reject':

                break;
            case 'block':

                break;
        }
    }

    public function getStatus($action,$ward=null){
        $wards=Users_guardian::where('guardian_id',Auth::user()->name)->first();
        return $wards;
    }

    public function viewWard($id, Request $request)
    {
        $guardian = new GuardianDataService();
        $data = $guardian->getGuardianData();
        $data['result'] = $guardian->getResults($id);
        $data['invoices'] = $guardian->getInvoices($id);
        $data['user'] = $id;
        $ward = User::where('name', $id)->first();
        $chart = new ChartController();

        $data['results'] = $chart->results($ward);
        $data['attendance_present'] = $chart->attendance('present', $ward);
        $data['attendance_absent'] = $chart->attendance('absent', $ward);
        $data['payments'] = $chart->payments($ward);
        return view('guardian.ward', $data);
    }

    public function getTimeTable(
        $id,
        Request $request
    ) // drg>> function services JSON request
    {
        $start = date('l', strtotime($request->start));
        $end = date('l', strtotime($request->end));

        $userData = new UndergraduateDataService($id);
        $user = Users_undergraduate::where('reg_no', $id)->first();
        $start = date('l', strtotime($start));
        $end = date('l', strtotime($end));
        $level = $userData->getLevel();
        $timeTable = TimeTable::join('users_staffs', 'time_table.lecturer',
            '=',
            'users_staffs.staff_id')->where(
            [
                [
                    'time_table.week_day',
                    '=',
                    DB::raw("'" . $start . "'")
                ],
                [
                    'time_table.dept',
                    '=',
                    $user->dept
                ],
                [
                    'time_table.faculty',
                    '=',
                    $user->faculty
                ],
                [
                    'time_table.level',
                    '=',
                    $level
                ]
            ])
            ->select(
                DB::raw(
                    "concat(time_table.course_code,' Lecture\nLocation: ', time_table.location,'\nLecturer: ',
						users_staffs.first_name ,' ', users_staffs.last_name, '.\nDuration: ', time_table.start_time, ' to ',
						time_table.end_time ) as title, time_table.start_time as start, time_table.end_time as end"))
            ->get();
        return $timeTable;

    }

    public function paymentInvoice($id,Request $request)
    {
        $invoices = $request->invoices;
        $fees = new FeesController();
        $userData = new UndergraduateDataService($id);
        $payment
            = true; // drg >> flag to indicate that invoice is for a payment transaction
        $lines = Invoice_line::whereIn('invoice_id', $invoices)
            ->orderBy('invoice_id', 'desc')->orderBy('item', 'desc')->get();

        $amount = $fees->totalInvoice($invoices);

        $charge = $fees->calcTransactionCharge($amount);
        $transactionCharge = $charge < 2500 ? $charge : 2500;
        $invoice['invoices'] = $invoices;
        $invoice['student'] = $id;
        $invoice['amount'] = $amount * 100;
        $invoice['charge'] = $transactionCharge * 100;

        $request->session()->flash('invoice', (object)$invoice);
        $data = (object)['user_meta' => $userData->getUsersMeta()];
        //var_dump($data);exit;
        $results = View::make('student.undergraduate.partials.invoiceList',
            compact('lines', 'payment', 'data'));
        $html = $results->render();

        return response()->json([
            'html' => $html
        ]);
    }

    public function viewProfile(){
        return view('guardian.profile');
    }
}

resources/views/guardian/home.blade.php
@php
    $public='';
    if(config('app.env') == 'production')
         $public ='public';
$data = session('userData');
    $wards = $data->wards;
@endphp
@extends('layouts.guardian.global')
@section('title','Home')
@section('style')
    <link rel='stylesheet' href="{{asset($public.'/css/fullcalendar.css')}}"/>
@endsection('style')
@section('content')
    <div class="content">
        <a class="block block-bordered text-center d-sm-none" href="javascript:void(0)" data-toggle="class-toggle"
           data-target=".js-classic-nav" data-class="d-none d-sm-block">
            <div class="block-content block-content-full text-center">
                <div class="font-w600 text-uppercase">
                    <i class="fa fa-bars mr-1"></i> Navigation
                </div>
            </div>
        </a>
        <div class="row">
            @php
                $background = ["$public/jpg/photo15.jpg", "$public/jpg/photo4.jpg", "$public/jpg/photo1.jpg", "$public/jpg/photo3.jpg"];
            @endphp
            @foreach($wards['active'] as $ward)
                <div class="col-md-6 col-xl-3 animated fadeIn" data-toggle="appear">
                    <div class="block block-rounded text-center">
                        <div class="block-content block-content-full bg-image"
                             style="background-image: url('{{$background[array_rand($background)]}}');">
                            <img class="img-avatar img-avatar-thumb" src="{{asset($public.'/'.$ward->photo_location)}}" alt="">
                        </div>
                        <div class="block-content block-content-full block-content-sm bg-body-light">
                            <div class="font-w600">{{$ward->first_name.' '.$ward->last_name}}</div>
                            <div class="font-size-sm text-muted">{{$ward->reg_no}}</div>
                        </div>
                        <div class="block-content block-content-full">
                            <a class="btn btn-sm btn-light" href="{{url("/guardian/view/$ward->reg_no")}}">
                                <i class="fa fa-user-circle text-muted mr-1"></i> View Ward
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="row">
            <div class="block block-rounded block-bordered">
                <div class="block-header block-header-default">
                    <h3 class="block-title">School Calendar
                        <small>Dates and Events</small>
                    </h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-toggle="block-option"
                                data-action="close">
                            <i class="si si-close"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-toggle="block-option"
                                data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                        <button type="button" class="btn-block-option" data-toggle="block-option"
                                data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                    </div>
                </div>
                <div class="block-content">
                    <div class="calendar" id="school-calendar"></div>
                </div>
            </div>
        </div>
    </div>
@endsection @section('script')
    <script type='text/javascript' src="{{asset($public.'/js/moment.min.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'/js/fullcalendar.js')}}"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#school-calendar').fullCalendar({
            // put your options and callbacks here
            aspectRatio: 1.5,
            header: {
                right: 'prev,next today',
                center: 'title',
                left: 'month,listWeek'
            },
            fixedWeekCount: false,
            contentHeight: 'auto',
            navLinks: true,
            startParam: 'start',
            endParam: 'end',
            //
            events: {
                url: '{{url("home/getevents")}}',
                type: 'POST',
                data: {
                    type: 'calendar',
                },
                error: function () {
                    alert('there was an error while fetching events!');
                },
                color: '#2CAC5C',   // a non-ajax option
                textColor: '#f5f5f5' // a non-ajax option
            }

        });
    </script>

@endsection

resources/views/guardian/newProfile.blade.php
@php
    $public='';
    if(config('app.env') == 'production')
    $public ='public';
        $background = ["$public/jpg/photo15.jpg", "$public/jpg/photo4.jpg", "$public/jpg/photo1.jpg", "$public/jpg/photo3.jpg"];

    $viewedWard=[];
@endphp
@extends('layouts.guardian.global')
@section('style')
    <link rel='stylesheet' href="{{asset($public.'/css/fullcalendar.css')}}"/>
    <link rel='stylesheet' href="{{asset($public.'/css/dropzone.min.css')}}"/>
@endsection
@section('title','Profile')
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="js-wizard-simple block block block-rounded block-bordered">
                    <ul class="nav nav-tabs nav-tabs-block nav-justified" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" href="#step1" data-toggle="tab">1. Personal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#step2" data-toggle="tab">2. Details</a>
                        </li>
                        {{--<li class="nav-item">
                            <a class="nav-link" href="#step3" data-toggle="tab">3. Photo</a>
                        </li>--}}
                    </ul>

                    <div class="block-content block-content-sm">
                        <div class="progress" data-wizard="progress" style="height: 8px;">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
                                 role="progressbar" style="width: 30%;" aria-valuenow="30" aria-valuemin="0"
                                 aria-valuemax="100"></div>
                        </div>
                    </div>
                    <form action="{{route('guardian.settings.profile')}}" method="post" id="profile-form">
                        {{csrf_field()}}
                        <div class="block-content block-content-full tab-content" style="min-height: 300px;">

                            <div class="tab-pane active" id="step1" role="tabpanel">
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input class="form-control" type="text" id="username"
                                           value="{{Auth::user()->name}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    <input class="form-control" type="text" id="first_name"
                                           name="first_name" placeholder="What's your first name?" required>
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <input class="form-control" type="text" id="last_name"
                                           name="last_name" placeholder="What's your last name?" required>
                                </div>
                            </div>
                            <div class="tab-pane" id="step2" role="tabpanel">
                                <div class="form-group">
                                    <label class="d-block">Gender</label>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" id="gender1" name="gender" required value="male"
                                               type="radio">
                                        <label class="form-check-label" for="gender1">Male</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" id="gender2" name="gender" required
                                               value="female"
                                               type="radio">
                                        <label class="form-check-label" for="gender2">Female</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="address">Address</label>
                                    <input class="form-control" type="text" id="address"
                                           name="address" placeholder="Where do you live?" required>
                                </div>
                                <div class="form-group">
                                    <label for="phone">Phone Number</label>
                                    <input class="form-control" id="phone" name="phone_no"
                                           placeholder="+234 0999 999 9999" type="text" required>
                                </div>
                            </div>

                            {{--<div class="tab-pane" id="step3" role="tabpanel">
                                <div class="form-group">
                                    <div class="block-content block-content-full">
                                        <h2
                                                class="content-heading">Asynchronous File Uploads</h2>
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <p class="text-muted">
                                                    Drag and drop photo for your file uploads
                                                </p>
                                                <p class="text-muted">
                                                    Your photo will be resized to 400x400, so upload a photo with
                                                    corresponding dimensions
                                                </p>
                                            </div>
                                            <div class="col-lg-8 col-xl-5">
                                                <div class="dropzone" id="photo"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>--}}

                        </div>
                    </form>
                    <div class="block-content block-content-sm block-content-full bg-body-light rounded-bottom">
                        <div class="row">
                            <div class="col-6">
                                <button type="button" class="btn btn-secondary" data-wizard="prev">
                                    <i class="fa fa-angle-left mr-1"></i> Previous
                                </button>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="btn btn-secondary" data-wizard="next">
                                    Next <i class="fa fa-angle-right ml-1"></i>
                                </button>
                                <button type="submit" class="btn btn-primary d-none" data-wizard="finish"
                                        form="profile-form" id="submit-button">
                                    <i class="fa fa-check mr-1"></i> Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type='text/javascript' src="{{asset($public.'/js/jquery.bootstrap.wizard.min.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'/js/jquery.validate.min.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'js/additional-methods.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'/js/be_forms_wizard.min.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'/js/jquery.maskedinput.min.js')}}"></script>
    <script type='text/javascript' src="{{asset($public.'/js/dropzone.js')}}"></script>
    <script>
        $('#phone').mask("+234 0999 999 9999");
        Dropzone.autoDiscover=false;
        var myDropzone = new Dropzone("div#photo", {
            url: "{{route('guardian.settings.photo')}}",
            paramName: 'photo',
            maxFiles: 1,
            acceptedFiles: 'image/*',
            resizeWidth: 400,
            resizeHeight: 400,
            processing: function (file) {
                //$('#submit-button').attr('disabled', '');
            },
            success: function (file, done) {
           //     $('#submit-button').removeAttr('disabled');
            }
        });
    </script>
@endsection